# Generated by Django 4.2 on 2024-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gelatina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descipcion', models.TextField()),
                ('imagen', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('tamanio', models.CharField(choices=[('PQ', 'Pequeño'), ('MD', 'Mediano'), ('GR', 'Grande')], max_length=50)),
            ],
        ),
    ]
